# ===========================
# SwiftLint Configuration
# ===========================

included:
  - Downapp
  - Modules

disabled_rules:
  - trailing_whitespace
  - todo
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - closure_spacing
  - sorted_imports
  - explicit_init

excluded:
  - Pods
  - Carthage
  - DerivedData
  - .build

# Настройки
line_length:
  warning: 150
  error: 200

identifier_name:
  min_length: 2
  excluded: ["id", "x", "y"]

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 80
  error: 150
